kind: Deployment
apiVersion: apps/v1
metadata:
  name: quotes
  labels:
    app: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
        - name: quotes
          env:
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: DB_NAME
              value: quotesdb
            - name: DB_SERVICE_NAME
              value: mysql
            - name: DB_PORT
              value: "3306"
          image: quay.io/eugene_butan/quotes:v7
          resources:
            limits:
              cpu: "1"
              memory: 750Mi
            requests:
              cpu: 10m
              memory: 64Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
              protocol: TCP
